### ISSUE TITLE
User Flow stopped working on Sketch 3.8.1

### ISSUE THREAD

**Issue by emkey** [abynim/UserFlows#11]
UserFlows stopped working on sketch 3.8.1. It creates the bitmaps but the it does not export it to the proper page designated and the does not create a proper canvas

**Comment by nicksinthemix** [comment]
![screen shot 2016-07-15 at 4 08 06 pm](https://cloud.githubusercontent.com/assets/10508885/16865217/5c95bb6a-4aa6-11e6-8fba-50ea0d474283.png)

I think I am seeing the same thing

**Comment by abynim** [comment]
Please use the latest version of the plugin.
