### ISSUE TITLE
Feature request: Annotation description per page

### ISSUE THREAD

**Issue by SanderWehkamp** [abynim/UserFlows#4]
I would like to be able to set description per page. Now i make them manually. Just underneath the image would be great!

**Comment by abynim** [comment]
@SanderWehkamp I just added this feature. Please check the ReadMe file to see how to use it, and let me know if it is similar to what you were expecting. Get the latest version from the repository: https://github.com/abynim/UserFlows/archive/master.zip

**Comment by SanderWehkamp** [comment]
Late Reply, But its nice thank you.
