### ISSUE TITLE
Plugin not working in Sketch v3.4.4

### ISSUE THREAD

**Issue by rpt1700** [abynim/UserFlows#5]
I updated to Sketch 3.4.4. When I attempt to generate a flow, the flow is generated incorrectly (a small artboard with nothing on it) on the incorrect page (always generates on the currently active page).

**Comment by abynim** [comment]
Thanks for reporting the issue. I believe it's been fixed in this latest update: https://github.com/abynim/UserFlows/archive/master.zip – Let me know if it still gives you any trouble.

**Comment by rpt1700** [comment]
Works like a charm. Thanks Aby!

...and seriously, thank you for this plugin. It saves me an incredible
amount of time.

- Art

On Sun, Dec 13, 2015 at 8:48 AM, Aby Nimbalkar <notifications@github.com>
wrote:

> Thanks for reporting the issue. I believe it's been fixed in this latest
> update: https://github.com/abynim/UserFlows/archive/master.zip – Let me
> know if it still gives you any trouble.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abynim/UserFlows/issues/5#issuecomment-164276764>.
>



-- 
Art

**Comment by abynim** [comment]
You're welcome!
