### ISSUE TITLE
Plugin broken in v3.4.4

### ISSUE THREAD

**Issue by ejschmidt** [abynim/UserFlows#6]
I too have discovered User Flow is broken with the v3.4.4 update to sketch. I LOVE this plugin! It saves me hours, and I DEPEND on it. 
On "Generate", app creates a tiny/empty artboard on the current page. It ignores commands to create a new page, or load into another page.

**Comment by abynim** [comment]
Just pushed a fix. Please replace the existing plugin bundle with the updated version from here: https://github.com/abynim/UserFlows/archive/master.zip – And let me know if it works for you.

**Comment by ejschmidt** [comment]
Aby—

YES!!! Thank you so much for fixing this. I really have become quite dependent on this plugin to keep my work flowing (pun intended). What a great treat to start my Monday morning. On the way into the office I was thinking about how much time today I would waste building flows manually, and how could I make it any faster. You saved my Monday for sure. If there is somewhere to add a positive review to your plugin, let me know. I’d be happy to write one!


Cheers,
Erich

Erich Schmidt | Senior UX Designer | O: 650-352-1132 x2019 | M: 650-218-8223 | www.weatherbug.com<http://weather.weatherbug.com>

**Comment by abynim** [comment]
Awesome! Great to know that you find the plugin useful. I was hoping to fix it over the weekend, just in time for Monday madness :) Glad it all worked out!
