### ISSUE TITLE
Plugin not working in Sketch 3.6.1

### ISSUE THREAD

**Issue by wilsoniwano** [abynim/UserFlows#8]
Hi there.

UserFlows isn't working in Sketch 3.6.1.
I think this plugin is very useful.
Is there a fix for this issue?

Thanks!

**Comment by abynim** [comment]
@wilsoniwano I tested the plugin in 3.6.1 and it seemed to work fine. What part is broken for you? Try deleting and installing the plugin again, just to be sure :)
